/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as FanRouteImport } from './routes/fan'
import { Route as StudioIndexRouteImport } from './routes/_studio/index'
import { Route as StudioAnalyticsRouteImport } from './routes/_studio/analytics'
import { Route as StudioArenaRouteImport } from './routes/_studio/arena'
import { Route as StudioLeaderboardRouteImport } from './routes/_studio/leaderboard'
import { Route as StudioMomentAgentRouteImport } from './routes/_studio/moment-agent'
import { Route as StudioObsOverlayRouteImport } from './routes/_studio/obs-overlay'
import { Route as StudioOverlayControlRouteImport } from './routes/_studio/overlay-control'
import { Route as StudioPlansRouteImport } from './routes/_studio/plans'
import { Route as StudioPredictionsRouteImport } from './routes/_studio/predictions'
import { Route as StudioPulseRouteImport } from './routes/_studio/pulse'
import { Route as StudioRivalsRouteImport } from './routes/_studio/rivals'
import { Route as StudioSetToolsRouteImport } from './routes/_studio/set-tools'
import { Route as StudioSettingsRouteImport } from './routes/_studio/settings'
import { Route as StudioSupportRouteImport } from './routes/_studio/support'
import { Route as StudioTeamRouteImport } from './routes/_studio/team'
import { Route as StudioVisionRouteImport } from './routes/_studio/vision'
import { Route as OverlaySlugRouteImport } from './routes/overlay.$slug'
import { Route as StudioPulseIndexRouteImport } from './routes/_studio/pulse/index'
import { Route as StudioPulseOnboardingRouteImport } from './routes/_studio/pulse/onboarding'

const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const FanRoute = FanRouteImport.update({
  id: '/fan',
  path: '/fan',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAnalyticsRoute = StudioAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => StudioRoute,
} as any)
const StudioArenaRoute = StudioArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLeaderboardRoute = StudioLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => StudioRoute,
} as any)
const StudioMomentAgentRoute = StudioMomentAgentRouteImport.update({
  id: '/moment-agent',
  path: '/moment-agent',
  getParentRoute: () => StudioRoute,
} as any)
const StudioObsOverlayRoute = StudioObsOverlayRouteImport.update({
  id: '/obs-overlay',
  path: '/obs-overlay',
  getParentRoute: () => StudioRoute,
} as any)
const StudioOverlayControlRoute = StudioOverlayControlRouteImport.update({
  id: '/overlay-control',
  path: '/overlay-control',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPlansRoute = StudioPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPredictionsRoute = StudioPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPulseRoute = StudioPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => StudioRoute,
} as any)
const StudioRivalsRoute = StudioRivalsRouteImport.update({
  id: '/rivals',
  path: '/rivals',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSetToolsRoute = StudioSetToolsRouteImport.update({
  id: '/set-tools',
  path: '/set-tools',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSettingsRoute = StudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSupportRoute = StudioSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => StudioRoute,
} as any)
const StudioTeamRoute = StudioTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => StudioRoute,
} as any)
const StudioVisionRoute = StudioVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => StudioRoute,
} as any)
const OverlaySlugRoute = OverlaySlugRouteImport.update({
  id: '/overlay/$slug',
  path: '/overlay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioPulseIndexRoute = StudioPulseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioPulseRoute,
} as any)
const StudioPulseOnboardingRoute = StudioPulseOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => StudioPulseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StudioIndexRoute
  '/fan': typeof FanRoute
  '/analytics': typeof StudioAnalyticsRoute
  '/arena': typeof StudioArenaRoute
  '/leaderboard': typeof StudioLeaderboardRoute
  '/moment-agent': typeof StudioMomentAgentRoute
  '/obs-overlay': typeof StudioObsOverlayRoute
  '/overlay-control': typeof StudioOverlayControlRoute
  '/plans': typeof StudioPlansRoute
  '/predictions': typeof StudioPredictionsRoute
  '/pulse': typeof StudioPulseRouteWithChildren
  '/rivals': typeof StudioRivalsRoute
  '/set-tools': typeof StudioSetToolsRoute
  '/settings': typeof StudioSettingsRoute
  '/support': typeof StudioSupportRoute
  '/team': typeof StudioTeamRoute
  '/vision': typeof StudioVisionRoute
  '/overlay/$slug': typeof OverlaySlugRoute
  '/pulse/onboarding': typeof StudioPulseOnboardingRoute
  '/pulse/': typeof StudioPulseIndexRoute
}
export interface FileRoutesByTo {
  '/fan': typeof FanRoute
  '/analytics': typeof StudioAnalyticsRoute
  '/arena': typeof StudioArenaRoute
  '/leaderboard': typeof StudioLeaderboardRoute
  '/moment-agent': typeof StudioMomentAgentRoute
  '/obs-overlay': typeof StudioObsOverlayRoute
  '/overlay-control': typeof StudioOverlayControlRoute
  '/plans': typeof StudioPlansRoute
  '/predictions': typeof StudioPredictionsRoute
  '/rivals': typeof StudioRivalsRoute
  '/set-tools': typeof StudioSetToolsRoute
  '/settings': typeof StudioSettingsRoute
  '/support': typeof StudioSupportRoute
  '/team': typeof StudioTeamRoute
  '/vision': typeof StudioVisionRoute
  '/overlay/$slug': typeof OverlaySlugRoute
  '/': typeof StudioIndexRoute
  '/pulse/onboarding': typeof StudioPulseOnboardingRoute
  '/pulse': typeof StudioPulseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_studio': typeof StudioRouteWithChildren
  '/fan': typeof FanRoute
  '/_studio/analytics': typeof StudioAnalyticsRoute
  '/_studio/arena': typeof StudioArenaRoute
  '/_studio/leaderboard': typeof StudioLeaderboardRoute
  '/_studio/moment-agent': typeof StudioMomentAgentRoute
  '/_studio/obs-overlay': typeof StudioObsOverlayRoute
  '/_studio/overlay-control': typeof StudioOverlayControlRoute
  '/_studio/plans': typeof StudioPlansRoute
  '/_studio/predictions': typeof StudioPredictionsRoute
  '/_studio/pulse': typeof StudioPulseRouteWithChildren
  '/_studio/rivals': typeof StudioRivalsRoute
  '/_studio/set-tools': typeof StudioSetToolsRoute
  '/_studio/settings': typeof StudioSettingsRoute
  '/_studio/support': typeof StudioSupportRoute
  '/_studio/team': typeof StudioTeamRoute
  '/_studio/vision': typeof StudioVisionRoute
  '/overlay/$slug': typeof OverlaySlugRoute
  '/_studio/': typeof StudioIndexRoute
  '/_studio/pulse/onboarding': typeof StudioPulseOnboardingRoute
  '/_studio/pulse/': typeof StudioPulseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fan'
    | '/analytics'
    | '/arena'
    | '/leaderboard'
    | '/moment-agent'
    | '/obs-overlay'
    | '/overlay-control'
    | '/plans'
    | '/predictions'
    | '/pulse'
    | '/rivals'
    | '/set-tools'
    | '/settings'
    | '/support'
    | '/team'
    | '/vision'
    | '/overlay/$slug'
    | '/pulse/onboarding'
    | '/pulse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/fan'
    | '/analytics'
    | '/arena'
    | '/leaderboard'
    | '/moment-agent'
    | '/obs-overlay'
    | '/overlay-control'
    | '/plans'
    | '/predictions'
    | '/rivals'
    | '/set-tools'
    | '/settings'
    | '/support'
    | '/team'
    | '/vision'
    | '/overlay/$slug'
    | '/'
    | '/pulse/onboarding'
    | '/pulse'
  id:
    | '__root__'
    | '/_studio'
    | '/fan'
    | '/_studio/analytics'
    | '/_studio/arena'
    | '/_studio/leaderboard'
    | '/_studio/moment-agent'
    | '/_studio/obs-overlay'
    | '/_studio/overlay-control'
    | '/_studio/plans'
    | '/_studio/predictions'
    | '/_studio/pulse'
    | '/_studio/rivals'
    | '/_studio/set-tools'
    | '/_studio/settings'
    | '/_studio/support'
    | '/_studio/team'
    | '/_studio/vision'
    | '/overlay/$slug'
    | '/_studio/'
    | '/_studio/pulse/onboarding'
    | '/_studio/pulse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StudioRoute: typeof StudioRouteWithChildren
  FanRoute: typeof FanRoute
  OverlaySlugRoute: typeof OverlaySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan': {
      id: '/fan'
      path: '/fan'
      fullPath: '/fan'
      preLoaderRoute: typeof FanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/': {
      id: '/_studio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/analytics': {
      id: '/_studio/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof StudioAnalyticsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/arena': {
      id: '/_studio/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof StudioArenaRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/leaderboard': {
      id: '/_studio/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof StudioLeaderboardRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/moment-agent': {
      id: '/_studio/moment-agent'
      path: '/moment-agent'
      fullPath: '/moment-agent'
      preLoaderRoute: typeof StudioMomentAgentRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/obs-overlay': {
      id: '/_studio/obs-overlay'
      path: '/obs-overlay'
      fullPath: '/obs-overlay'
      preLoaderRoute: typeof StudioObsOverlayRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/overlay-control': {
      id: '/_studio/overlay-control'
      path: '/overlay-control'
      fullPath: '/overlay-control'
      preLoaderRoute: typeof StudioOverlayControlRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/plans': {
      id: '/_studio/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof StudioPlansRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/predictions': {
      id: '/_studio/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof StudioPredictionsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/pulse': {
      id: '/_studio/pulse'
      path: '/pulse'
      fullPath: '/pulse'
      preLoaderRoute: typeof StudioPulseRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/rivals': {
      id: '/_studio/rivals'
      path: '/rivals'
      fullPath: '/rivals'
      preLoaderRoute: typeof StudioRivalsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/set-tools': {
      id: '/_studio/set-tools'
      path: '/set-tools'
      fullPath: '/set-tools'
      preLoaderRoute: typeof StudioSetToolsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/settings': {
      id: '/_studio/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof StudioSettingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/support': {
      id: '/_studio/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof StudioSupportRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/team': {
      id: '/_studio/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof StudioTeamRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/vision': {
      id: '/_studio/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof StudioVisionRouteImport
      parentRoute: typeof StudioRoute
    }
    '/overlay/$slug': {
      id: '/overlay/$slug'
      path: '/overlay/$slug'
      fullPath: '/overlay/$slug'
      preLoaderRoute: typeof OverlaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/pulse/': {
      id: '/_studio/pulse/'
      path: '/'
      fullPath: '/pulse/'
      preLoaderRoute: typeof StudioPulseIndexRouteImport
      parentRoute: typeof StudioPulseRoute
    }
    '/_studio/pulse/onboarding': {
      id: '/_studio/pulse/onboarding'
      path: '/onboarding'
      fullPath: '/pulse/onboarding'
      preLoaderRoute: typeof StudioPulseOnboardingRouteImport
      parentRoute: typeof StudioPulseRoute
    }
  }
}

interface StudioPulseRouteChildren {
  StudioPulseOnboardingRoute: typeof StudioPulseOnboardingRoute
  StudioPulseIndexRoute: typeof StudioPulseIndexRoute
}

const StudioPulseRouteChildren: StudioPulseRouteChildren = {
  StudioPulseOnboardingRoute: StudioPulseOnboardingRoute,
  StudioPulseIndexRoute: StudioPulseIndexRoute,
}

const StudioPulseRouteWithChildren = StudioPulseRoute._addFileChildren(
  StudioPulseRouteChildren,
)

interface StudioRouteChildren {
  StudioAnalyticsRoute: typeof StudioAnalyticsRoute
  StudioArenaRoute: typeof StudioArenaRoute
  StudioLeaderboardRoute: typeof StudioLeaderboardRoute
  StudioMomentAgentRoute: typeof StudioMomentAgentRoute
  StudioObsOverlayRoute: typeof StudioObsOverlayRoute
  StudioOverlayControlRoute: typeof StudioOverlayControlRoute
  StudioPlansRoute: typeof StudioPlansRoute
  StudioPredictionsRoute: typeof StudioPredictionsRoute
  StudioPulseRoute: typeof StudioPulseRouteWithChildren
  StudioRivalsRoute: typeof StudioRivalsRoute
  StudioSetToolsRoute: typeof StudioSetToolsRoute
  StudioSettingsRoute: typeof StudioSettingsRoute
  StudioSupportRoute: typeof StudioSupportRoute
  StudioTeamRoute: typeof StudioTeamRoute
  StudioVisionRoute: typeof StudioVisionRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAnalyticsRoute: StudioAnalyticsRoute,
  StudioArenaRoute: StudioArenaRoute,
  StudioLeaderboardRoute: StudioLeaderboardRoute,
  StudioMomentAgentRoute: StudioMomentAgentRoute,
  StudioObsOverlayRoute: StudioObsOverlayRoute,
  StudioOverlayControlRoute: StudioOverlayControlRoute,
  StudioPlansRoute: StudioPlansRoute,
  StudioPredictionsRoute: StudioPredictionsRoute,
  StudioPulseRoute: StudioPulseRouteWithChildren,
  StudioRivalsRoute: StudioRivalsRoute,
  StudioSetToolsRoute: StudioSetToolsRoute,
  StudioSettingsRoute: StudioSettingsRoute,
  StudioSupportRoute: StudioSupportRoute,
  StudioTeamRoute: StudioTeamRoute,
  StudioVisionRoute: StudioVisionRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StudioRoute: StudioRouteWithChildren,
  FanRoute: FanRoute,
  OverlaySlugRoute: OverlaySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
